/**
 * This file is normally generated by the Supabase CLI:
 *
 *   npm run gen:types
 *
 * It's checked in by hand for now so the app compiles before a real
 * Supabase project exists. Once you run migrations against a real project,
 * regenerate this file and delete this comment — the shape below mirrors
 * the schema from the architecture doc so nothing downstream should need to
 * change.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string;
          avatar_url: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          display_name: string;
          avatar_url?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
        Relationships: [];
      };
      daily_prompts: {
        Row: {
          id: string;
          prompt_text: string;
          active: boolean;
        };
        Insert: {
          id?: string;
          prompt_text: string;
          active?: boolean;
        };
        Update: Partial<
          Database["public"]["Tables"]["daily_prompts"]["Insert"]
        >;
        Relationships: [];
      };
      families: {
        Row: {
          id: string;
          name: string;
          invite_code: string;
          timezone: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          invite_code?: string;
          timezone?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["families"]["Insert"]>;
        Relationships: [];
      };
      family_members: {
        Row: {
          id: string;
          family_id: string;
          user_id: string;
          role: "parent" | "kid" | "other";
          joined_at: string;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          family_id: string;
          user_id: string;
          role?: "parent" | "kid" | "other";
          joined_at?: string;
          is_active?: boolean;
        };
        Update: Partial<
          Database["public"]["Tables"]["family_members"]["Insert"]
        >;
        Relationships: [];
      };
      check_in_days: {
        Row: {
          id: string;
          family_id: string;
          date: string;
          prompt_id: string | null;
          status: "open" | "unlocked";
          unlocked_at: string | null;
        };
        Insert: {
          id?: string;
          family_id: string;
          date: string;
          prompt_id?: string | null;
          status?: "open" | "unlocked";
          unlocked_at?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["check_in_days"]["Insert"]
        >;
        Relationships: [];
      };
      entries: {
        Row: {
          id: string;
          check_in_day_id: string;
          user_id: string;
          type: "text" | "voice" | "photo";
          text_content: string | null;
          media_url: string | null;
          media_duration_sec: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          check_in_day_id: string;
          user_id: string;
          type: "text" | "voice" | "photo";
          text_content?: string | null;
          media_url?: string | null;
          media_duration_sec?: number | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["entries"]["Insert"]>;
        Relationships: [];
      };
      journal_entries: {
        Row: {
          id: string;
          user_id: string;
          type: "text" | "voice" | "photo";
          text_content: string | null;
          media_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: "text" | "voice" | "photo";
          text_content?: string | null;
          media_url?: string | null;
          created_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["journal_entries"]["Insert"]
        >;
        Relationships: [];
      };
      island_state: {
        Row: {
          id: string;
          family_id: string;
          growth_level: number;
          updated_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          growth_level?: number;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["island_state"]["Insert"]
        >;
        Relationships: [];
      };
      family_decorations: {
        Row: {
          id: string;
          family_id: string;
          decoration_id: string;
          check_in_day_id: string;
          placed_at: string;
          asset_key: string | null;
          object_type: string | null;
          rarity: string | null;
          placement_zone: string | null;
          position_x: number | null;
          position_y: number | null;
          z_index: number | null;
          unlocked_at: string | null;
          linked_memory_summary: string | null;
          placement_status: "pending_placement" | "placed" | "stored";
          placed_by: string | null;
          stored_at: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          decoration_id: string;
          check_in_day_id: string;
          placed_at?: string;
          asset_key?: string | null;
          object_type?: string | null;
          rarity?: string | null;
          placement_zone?: string | null;
          position_x?: number | null;
          position_y?: number | null;
          z_index?: number | null;
          unlocked_at?: string | null;
          linked_memory_summary?: string | null;
          placement_status?: "pending_placement" | "placed" | "stored";
          placed_by?: string | null;
          stored_at?: string | null;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["family_decorations"]["Insert"]
        >;
        Relationships: [];
      };
      island_placement_slots: {
        Row: { id: string; zone: string; position_x: number; position_y: number; z_index: number };
        Insert: { id?: string; zone: string; position_x: number; position_y: number; z_index: number };
        Update: Partial<Database["public"]["Tables"]["island_placement_slots"]["Insert"]>;
        Relationships: [];
      };
      island_memory_objects: {
        Row: {
          id: string;
          family_id: string;
          memory_id: string;
          object_type: "wildflower" | "leafy_plant" | "mushroom" | "flower_stone" | "young_sapling";
          position_x: number;
          position_y: number;
          scale: number;
          rotation: number;
          growth_stage: number;
          placed_by: string;
          placed_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          memory_id: string;
          object_type: "wildflower" | "leafy_plant" | "mushroom" | "flower_stone" | "young_sapling";
          position_x: number;
          position_y: number;
          scale?: number;
          rotation?: number;
          growth_stage?: number;
          placed_by: string;
          placed_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["island_memory_objects"]["Insert"]>;
        Relationships: [];
      };
    };
    Functions: {
      create_family: {
        Args: { p_name: string };
        Returns: Database["public"]["Tables"]["families"]["Row"];
      };
      join_family: {
        Args: { p_invite_code: string };
        Returns: Database["public"]["Tables"]["families"]["Row"];
      };
      select_daily_island_reward: {
        Args: { p_family_id: string; p_family_day_id: string; p_season?: string | null };
        Returns: Database["public"]["Tables"]["family_decorations"]["Row"];
      };
      place_memory_seed: {
        Args: {
          p_memory_id: string;
          p_object_type: string;
          p_position_x: number;
          p_position_y: number;
          p_scale?: number;
          p_rotation?: number;
        };
        Returns: Database["public"]["Tables"]["island_memory_objects"]["Row"];
      };
      place_family_day_reward: {
        Args: { p_reward_id: string; p_position_x: number; p_position_y: number };
        Returns: Database["public"]["Tables"]["family_decorations"]["Row"];
      };
      move_family_day_reward: {
        Args: { p_reward_id: string; p_position_x: number; p_position_y: number };
        Returns: Database["public"]["Tables"]["family_decorations"]["Row"];
      };
      store_family_day_reward: {
        Args: { p_reward_id: string };
        Returns: Database["public"]["Tables"]["family_decorations"]["Row"];
      };
    };
    Views: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
