import type { IslandObjectRecord } from "../types";

/**
 * This file is the ONE prototype scene requested to verify layering,
 * scale, spacing, and visual direction — hand-placed for an intentional
 * composition (cabin as focal point, open space reserved for growth)
 * rather than run through `positionWithinZone`'s auto-scatter. Real
 * unlocked objects, once wired to actual family data in api.ts, use the
 * zone algorithm instead; this file is deleted or gated behind a flag at
 * that point, not extended.
 */
export const MOCK_ISLAND_OBJECTS: IslandObjectRecord[] = [
  {
    id: "mock-tree-1",
    objectType: "tree",
    assetKey: "tree_pine_01",
    positionX: 43,
    positionY: 34,
    scale: 1.5,
    rotation: 0,
    zIndex: 11,
    unlockedAt: "2026-06-01",
    memoryId: null,
    name: "Sprout Pine",
  },
  {
    id: "mock-tree-2",
    objectType: "tree",
    assetKey: "tree_pine_01",
    positionX: 31,
    positionY: 54,
    scale: 1.45,
    rotation: -4,
    zIndex: 13,
    unlockedAt: "2026-06-08",
    memoryId: null,
    name: "Round Oak",
  },
  {
    id: "mock-tree-3",
    objectType: "tree",
    assetKey: "tree_pine_01",
    positionX: 69,
    positionY: 50,
    scale: 1.45,
    rotation: 3,
    zIndex: 12,
    unlockedAt: "2026-06-15",
    memoryId: null,
    name: "Sprout Pine",
  },
  {
    id: "mock-cabin",
    objectType: "building",
    assetKey: "cabin_01",
    positionX: 54,
    positionY: 56,
    scale: 2.15,
    rotation: 0,
    zIndex: 30,
    unlockedAt: "2026-05-20",
    memoryId: null,
    name: "Little Lantern Hut",
  },
  {
    id: "mock-bench",
    objectType: "furniture",
    assetKey: "bench_01",
    positionX: 70,
    positionY: 68,
    scale: 1.2,
    rotation: 0,
    zIndex: 35,
    unlockedAt: "2026-06-22",
    memoryId: null,
    name: "Cozy Bench",
  },
  {
    id: "mock-path",
    objectType: "furniture",
    assetKey: "path_stone_01",
    positionX: 36,
    positionY: 83,
    scale: 1.7,
    rotation: -8,
    zIndex: 20,
    unlockedAt: "2026-06-10",
    memoryId: null,
    name: "Garden Path",
  },
  {
    id: "mock-pond",
    objectType: "water",
    assetKey: "pond_01",
    positionX: 62,
    positionY: 79,
    scale: 2.2,
    rotation: 0,
    zIndex: 16,
    unlockedAt: "2026-05-25",
    memoryId: null,
    name: "Quiet Pond",
  },
  {
    id: "mock-flower-1",
    objectType: "flower",
    assetKey: "flower_cluster_01",
    positionX: 42,
    positionY: 70,
    scale: 1.35,
    rotation: 0,
    zIndex: 26,
    unlockedAt: "2026-06-05",
    memoryId: null,
    name: "Sunflower Patch",
  },
  {
    id: "mock-flower-2",
    objectType: "flower",
    assetKey: "flower_cluster_01",
    positionX: 78,
    positionY: 76,
    scale: 1.3,
    rotation: 6,
    zIndex: 28,
    unlockedAt: "2026-06-12",
    memoryId: null,
    name: "Wild Poppies",
  },
  {
    id: "mock-cat",
    objectType: "animal",
    assetKey: "cat_01",
    positionX: 47,
    positionY: 58,
    scale: 0.8,
    rotation: 0,
    zIndex: 40,
    unlockedAt: "2026-06-18",
    memoryId: null,
    name: "Napping Cat",
  },
];
